#!/usr/bin/env ruby

require 'bundler/setup'
require 'pry'
require 'pry-rails'
require 'zuokiq'
require 'optparse'

OptionParser.new do |opts|
  opts.banner = 'Usage: bundle exec octokiq [options]'

  opts.on '-r', '--require [PATH]', 'Location of file to require' do |arg|
    require File.expand_path(arg)
  end
end.parse!

server = Zuokiq::Server.new
server.start

